import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'RankMath- Task',
  description: 'Generated by Shreyansh',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="https://kit.fontawesome.com/f0e86dfbf8.js" crossorigin="anonymous"></script>
      </head>
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
